-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Allow admins to update any profile (for role management)
create policy "Admins can update any profile."
  on profiles for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Create a table for monthly targets
create table monthly_targets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  month integer not null check (month >= 1 and month <= 12),
  year integer not null,
  target_value text not null,
  description text,
  
  unique(month, year)
);

alter table monthly_targets enable row level security;

create policy "Targets are viewable by everyone."
  on monthly_targets for select
  using ( true );

create policy "Only admins can insert targets."
  on monthly_targets for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can update targets."
  on monthly_targets for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Create a table for submissions
create table submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  target_id bigint references monthly_targets not null,
  image_url text not null,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  
  unique(user_id, target_id)
);

alter table submissions enable row level security;

create policy "Submissions are viewable by everyone."
  on submissions for select
  using ( true );

create policy "Users can insert their own submission."
  on submissions for insert
  with check ( auth.uid() = user_id );

create policy "Only admins can update submission status."
  on submissions for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Storage buckets
insert into storage.buckets (id, name)
values ('submissions', 'submissions');

create policy "Submission images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'submissions' );

create policy "Users can upload submission images."
  on storage.objects for insert
  with check ( bucket_id = 'submissions' and auth.uid() = owner );
