-- ============================================
-- CLEANUP SCRIPT (Run this first if you have existing tables)
-- ============================================

-- Drop existing policies
drop policy if exists "Public profiles are viewable by everyone." on profiles;
drop policy if exists "Users can insert their own profile." on profiles;
drop policy if exists "Users can update own profile." on profiles;
drop policy if exists "Admins can update any profile." on profiles;
drop policy if exists "Targets are viewable by everyone." on monthly_targets;
drop policy if exists "Only admins can insert targets." on monthly_targets;
drop policy if exists "Only admins can update targets." on monthly_targets;
drop policy if exists "Submissions are viewable by everyone." on submissions;
drop policy if exists "Users can insert their own submission." on submissions;
drop policy if exists "Only admins can update submission status." on submissions;
drop policy if exists "Submission images are publicly accessible." on storage.objects;
drop policy if exists "Users can upload submission images." on storage.objects;

-- Drop existing tables
drop table if exists submissions;
drop table if exists monthly_targets;
drop table if exists profiles;

-- ============================================
-- CREATE TABLES
-- ============================================

-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  role text default 'user' check (role in ('user', 'admin')),

  constraint username_length check (char_length(username) >= 3)
);

-- Create a table for monthly targets
create table monthly_targets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  month integer not null check (month >= 1 and month <= 12),
  year integer not null,
  target_value text not null,
  description text,
  
  unique(month, year)
);

-- Create a table for submissions
create table submissions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users on delete cascade not null,
  target_id bigint references monthly_targets not null,
  image_url text not null,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  
  unique(user_id, target_id)
);

-- ============================================
-- ROW LEVEL SECURITY POLICIES
-- ============================================

-- Profiles RLS
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

create policy "Admins can update any profile."
  on profiles for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Monthly Targets RLS
alter table monthly_targets enable row level security;

create policy "Targets are viewable by everyone."
  on monthly_targets for select
  using ( true );

create policy "Only admins can insert targets."
  on monthly_targets for insert
  with check ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

create policy "Only admins can update targets."
  on monthly_targets for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- Submissions RLS
alter table submissions enable row level security;

create policy "Submissions are viewable by everyone."
  on submissions for select
  using ( true );

create policy "Users can insert their own submission."
  on submissions for insert
  with check ( auth.uid() = user_id );

create policy "Only admins can update submission status."
  on submissions for update
  using ( exists ( select 1 from profiles where id = auth.uid() and role = 'admin' ) );

-- ============================================
-- STORAGE SETUP
-- ============================================

-- Create storage bucket (if it doesn't exist)
insert into storage.buckets (id, name, public)
values ('submissions', 'submissions', true)
on conflict (id) do nothing;

-- Storage policies
create policy "Submission images are publicly accessible."
  on storage.objects for select
  using ( bucket_id = 'submissions' );

create policy "Users can upload submission images."
  on storage.objects for insert
  with check ( bucket_id = 'submissions' and auth.role() = 'authenticated' );

create policy "Users can update their own images."
  on storage.objects for update
  using ( bucket_id = 'submissions' and auth.role() = 'authenticated' );

create policy "Users can delete their own images."
  on storage.objects for delete
  using ( bucket_id = 'submissions' and auth.role() = 'authenticated' );

-- ============================================
-- TRIGGERS
-- ============================================

-- ============================================
-- TRIGGERS
-- ============================================

-- Function to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, full_name, role)
  values (
    new.id,
    coalesce(new.email, 'user_' || substr(new.id::text, 1, 8)), -- Fallback if email is null
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    'user'
  )
  on conflict (id) do nothing; -- Prevent error if profile already exists
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
